Add --timestamp (mostly for testing), factor out marker()

diff --git a/bin/memoizeCall b/bin/memoizeCall
--- a/bin/memoizeCall
+++ b/bin/memoizeCall
@@ -10,7 +10,7 @@ not error messages, --successful-only skips recording for failed commands so
 that the next invocation will retry) for later recalls (of the same COMMAND /
 SUBJECT [/ GROUP]).
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-t|--for VALID-TIMESPAN[SUFFIX]|second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks)] [--successful-only] [-g|--memoize-group GROUP] [-s|--subject SUBJECT] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-t|--for VALID-TIMESPAN[SUFFIX]|second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks)] [--timestamp EPOCH] [--successful-only] [-g|--memoize-group GROUP] [-s|--subject SUBJECT] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[...] [-?|-h|--help]'
     printf 'Usage: %q %s <<EOF\n  COMMANDLINE\n...\nEOF\n' "$(basename "$1")" '[...]'
 }
@@ -22,18 +22,20 @@ subject=
 isNeedEval=
 typeset -a commands=()
 isFromStandardIn=
+typeset -a executionMarkerArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--for|-t)	shift; validity="$1"; shift;;
+	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
+	--for|-t)		shift; validity="$1"; shift;;
+	--timestamp)		executionMarkerArgs+=("$1" "$2"); shift; shift;;
 	--successful-only)	shift; isSuccessfulOnly=t;;
 	--memoize-group|-g)	shift; group="$1"; shift;;
 	--subject|-s)		shift; subject="$1"; shift;;
-	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
-	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		break;;
+	--command|-c)		shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--)			shift; break;;
+	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)			break;;
     esac
 done
 if [ $# -ne 0 ]; then
@@ -58,12 +60,16 @@ fi
 
 [ "$subject" ] || subject="${commands[*]}"
 if [ "$namespace" ]; then
-    typeset -a executionMarkerArgs=(--namespace memoizeCall --group "$group")
+    executionMarkerArgs+=(--namespace memoizeCall --group "$group")
 else
-    typeset -a executionMarkerArgs=(--group memoizeCall)
+    executionMarkerArgs+=(--group memoizeCall)
 fi
+marker()
+{
+    executionMarker "${executionMarkerArgs[@]}" "$@"
+}
 
-if context="$(executionMarker "${executionMarkerArgs[@]}" --query "$subject" ${validity:+--within "$validity"} --get-context)"; then
+if context="$(marker --query "$subject" ${validity:+--within "$validity"} --get-context)"; then
     exitStatus="${context%% *}"
     output="${context#* }"
     [ "$output" ] && printf '%s\n' "$output"
@@ -84,5 +90,5 @@ exitStatus=$?
 [ "$output" ] && printf '%s\n' "$output"
 
 [ $exitStatus -ne 0 -a -n "$isSuccessfulOnly" ] && exit $exitStatus
-executionMarker "${executionMarkerArgs[@]}" --update "$subject" --context "$exitStatus $output"
+marker --update "$subject" --context "$exitStatus $output"
 exit $exitStatus
