memoizeDecision: Refactoring: Extract assertValidChoice()

diff --git a/bin/memoizeDecision b/bin/memoizeDecision
--- a/bin/memoizeDecision
+++ b/bin/memoizeDecision
@@ -102,6 +102,14 @@ EXIT STATUS:
     3 if memoization fails or the query times out without a given --default
 HELPTEXT
 }
+assertValidChoice()
+{
+    case "$1" in
+	confirm-each|c|yes|y|any|a|always|l|any-always|A|decline-each|d|no|n|none|o|never|v|none-never|N)
+	    return 0;;
+	*)  return 1;;
+    esac
+}
 
 group=
 subject=
@@ -125,12 +133,12 @@ do
 	--timeout)	shift; timeInSeconds="$(timeToSeconds "$1" timeout)" || exit $?; shift
 			timeoutPlural=s; [ "$timeInSeconds" = 1 ] && timeoutPlural=; timeout="Within $timeInSeconds second${timeoutPlural}: "; readArgs+=(-t "$timeInSeconds")
 			;;
-	--default|-d)	shift
-			case "$1" in
-			    confirm-each|c|yes|y|any|a|always|l|any-always|A|decline-each|d|no|n|none|o|never|v|none-never|N)
-				default=$1;;
-			    *)	printf >&2 'ERROR: Invalid default: %s\n' "$1"; exit 2;;
-			esac
+	--default|-d)	shift; if assertValidChoice "$1"; then
+			    default="$1"
+			else
+			    printf >&2 'ERROR: Invalid default: %s\n' "$1"
+			    exit 2
+			fi
 			shift
 			;;
 	--set-decision|-c)
