Renaming: MEMOIZEDECISION_VALID_TIMESPAN_SECONDS to MEMOIZEDECISION_VALID_INTERVAL and allow arbitrary units there
Since we have to convert a passed --timespan into seconds, anyway, we can accept arbitrary units in the default configuration, too.
Introduce validIntervalSeconds.
Rename config var to "interval" to be consistent, and drop the "seconds".

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/memoizeDecision b/bin/memoizeDecision
--- a/bin/memoizeDecision
+++ b/bin/memoizeDecision
@@ -23,7 +23,7 @@ shopt -qs extglob
 : ${MEMOIZEDECISION_POSITIVE_SUFFIX='[0m'}
 : ${MEMOIZEDECISION_NEGATIVE_PREFIX='[33m'}
 : ${MEMOIZEDECISION_NEGATIVE_SUFFIX='[0m'}
-: ${MEMOIZEDECISION_VALID_TIMESPAN_SECONDS:=900}
+: ${MEMOIZEDECISION_VALID_INTERVAL:=15m}
 
 readonly FOREVER_EPOCH=4294967295
 
@@ -79,7 +79,7 @@ MEMOIZEDECISION_CHOICE.
 				Recall a previous answer given for that GROUP
 				and SUBJECT if a previous invocation (with an
 				answer of yes/any/no/none) had happened within
-				TIMESPAN (default ${MEMOIZEDECISION_VALID_TIMESPAN_SECONDS} seconds).
+				TIMESPAN (default ${MEMOIZEDECISION_VALID_INTERVAL} seconds).
 				SUFFIX may be 's' for seconds (the default), 'm'
 				for minutes, 'h' for hours or 'd' for days.
     --recall-only		Do not query the user; just return a previous
@@ -158,6 +158,7 @@ action=
 default=
 decision=
 isRecallOnly=
+validIntervalSeconds=
 timeout=
 timeInSeconds=
 typeset -a readArgs=()
@@ -175,7 +176,7 @@ do
 	--verb)			shift; verb="$1"; shift;;
 	--state|-t)		shift; state="$1"; shift;;
 	--action|-a)		shift; action="$1"; shift;;
-	--timespan)		shift; MEMOIZEDECISION_VALID_TIMESPAN_SECONDS="$(durationToSeconds -- "${1:?}")" || { printf >&2 'ERROR: Illegal timespan: %s\n' "$1"; exit 2; }; shift;;
+	--timespan)		shift; validIntervalSeconds="$(durationToSeconds -- "${1:?}")" || { printf >&2 'ERROR: Illegal timespan: %s\n' "$1"; exit 2; }; shift;;
 	--recall-only)	shift; isRecallOnly=t;;
 	--timeout)	shift; timeInSeconds="$(durationToSeconds -- "${1:?}")" || { printf >&2 'ERROR: Illegal timeout: %s\n' "$1"; exit 2; }; shift
 			timeoutPlural=s; [ "$timeInSeconds" = 1 ] && timeoutPlural=; timeout="Within $timeInSeconds second${timeoutPlural}: "; readArgs+=(-t "$timeInSeconds")
@@ -226,6 +227,7 @@ do
 	*)		break;;
     esac
 done
+[ -n "$validIntervalSeconds" ] || validIntervalSeconds="$(durationToSeconds -- "$MEMOIZEDECISION_VALID_INTERVAL")" || { printf >&2 'ERROR: Invalid MEMOIZEDECISION_VALID_INTERVAL: %s\n' "$MEMOIZEDECISION_VALID_INTERVAL"; exit 2; }
 if [ $# -gt 0 ] || [ -z "$specialAction" -a \( -z "$group" -o -z "$subject" -o -z "$state" -o -z "$action" \) ]; then
     printUsage "$0"
     exit 2
@@ -259,7 +261,7 @@ hasMarker()
 {
     local subject=${1:?}; shift
     local escapedSubject="${subject//	/ }"
-    markerExitStatus="$(fallbackMarker --query "$escapedSubject" --newer "$MEMOIZEDECISION_VALID_TIMESPAN_SECONDS" --get-context)" || return $?
+    markerExitStatus="$(fallbackMarker --query "$escapedSubject" --newer "$validIntervalSeconds" --get-context)" || return $?
 }
 
 getMarkerExitStatusAndTimestamp()
@@ -278,7 +280,7 @@ getMarkerExitStatusAndTimestamp()
 }
 getMarkerSubjectAndExpiryAndExitStatusAndTimestamp()
 {
-    local validTimespanSeconds=$((MEMOIZEDECISION_VALID_TIMESPAN_SECONDS - 1 >= 0 ? MEMOIZEDECISION_VALID_TIMESPAN_SECONDS - 1 : 0))
+    local validTimespanSeconds=$((validIntervalSeconds - 1 >= 0 ? validIntervalSeconds - 1 : 0))
     markerSubject="${1:?}"
     markerIsExpired=
 
@@ -368,7 +370,7 @@ setDecision()
 
 getTimespanDuration()
 {
-    datediff --seconds "$MEMOIZEDECISION_VALID_TIMESPAN_SECONDS" --output best-unit --no-direction
+    datediff --seconds "$validIntervalSeconds" --output best-unit --no-direction
 }
 
 processChoice()
