memoize{Call,File,lines}: ENH: Minor: Consistency: Also support --exec
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/memoizeCall b/bin/memoizeCall
--- a/bin/memoizeCall
+++ b/bin/memoizeCall
@@ -2,13 +2,14 @@
 shopt -qs extglob
 
 : ${MEMOIZECALL_COMMAND_JOINER=;}
+: ${MEMOIZECALL_EXEC_END=;}
 : ${MEMOIZECALL_EXTERNALIZE_OUTPUT_THRESHOLD=20000}
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: [MEMOIZECALL_EXTERNALIZE_OUTPUT_THRESHOLD=BYTES] [MEMOIZECALL_FORCE_UPDATE=1|t|true|"SUBJECT-GLOB"] %q %s\n' "$(basename "$1")" '[-t|--for VALID-TIMESPAN[SUFFIX]|second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks)] [--timestamp EPOCH] [-S|--successful-only] [-g|--memoize-group GROUP] [-s|--subject SUBJECT] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    printf 'Usage: [MEMOIZECALL_EXTERNALIZE_OUTPUT_THRESHOLD=BYTES] [MEMOIZECALL_FORCE_UPDATE=1|t|true|"SUBJECT-GLOB"] %q %s\n' "$(basename "$1")" "[-t|--for VALID-TIMESPAN[SUFFIX]|second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks)] [--timestamp EPOCH] [-S|--successful-only] [-g|--memoize-group GROUP] [-s|--subject SUBJECT] -c|--command \"COMMANDLINE\" [-c ...] --exec SIMPLECOMMAND [...] ${MEMOIZECALL_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[...] [-?|-h|--help]'
     printf 'Usage: %q %s <<EOF\n  COMMANDLINE\n...\nEOF\n' "$(basename "$1")" '[...]'
 }
@@ -40,6 +41,9 @@ HELPDESCRIPTION
     --successful-only|-S
 			Skip recording for failed commands so that the next
 			invocation will retry the command.
+    --exec CMD [...] ${MEMOIZECALL_EXEC_END}	Execute CMD; all following arguments are taken to be
+			arguments to the CMD until an argument consisting of
+			'${MEMOIZECALL_EXEC_END}' is encountered.
 RELATED COMMANDS:
 - bash-cache (https://github.com/dimo414/bash-cache) transparently decorates a
   Bash function.
@@ -63,6 +67,21 @@ do
 	--memoize-group|-g)	shift; group="$1"; shift;;
 	--subject|-s)		shift; subject="$1"; shift;;
 	--command|-c)		shift; commands+="${commands:+ $MEMOIZECALL_COMMAND_JOINER }$1"; shift;;
+	--exec)			shift
+				cmd=
+				while [ $# -gt 0 -a "$1" != "$MEMOIZECALL_EXEC_END" ]
+				do
+				    printf -v quotedArg %q "$1"
+				    cmd+="${cmd:+ }${quotedArg}"
+				    shift
+				done
+				if [ $# -eq 0 ]; then
+				    echo "ERROR: --exec command must be concluded with '${MEMOIZECALL_EXEC_END}'"; echo; printUsage "$0"
+				    exit 2
+				fi >&2
+				shift
+				commands+="${commands:+ $MEMOIZECALL_COMMAND_JOINER }${cmd}"
+				;;
 	--)			shift; break;;
 	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)			break;;
diff --git a/bin/memoizeFile b/bin/memoizeFile
--- a/bin/memoizeFile
+++ b/bin/memoizeFile
@@ -2,6 +2,7 @@
 shopt -qs extglob
 
 : ${MEMOIZEFILE_COMMAND_JOINER=;}
+: ${MEMOIZEFILE_EXEC_END=;}
 : ${MEMOIZEFILE_FILE_MARKER='{}'}
 fileMarker="$MEMOIZEFILE_FILE_MARKER"; unset MEMOIZEFILE_FILE_MARKER
 
@@ -11,7 +12,7 @@ printShortUsage()
     echo
     printf 'Usage: cat SOURCE-FILE [...] | %q %s\n' "$(basename "$1")" "..."
     echo
-    printf 'Usage: %q %s %s\n' "$(basename "$1")" "$commonArgs" '... [-r|--redirect] [--tee] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...]'
+    printf 'Usage: %q %s %s\n' "$(basename "$1")" "$commonArgs" "... [-r|--redirect] [--tee] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${MEMOIZEFILE_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...]"
 }
 printUsage()
 {
@@ -56,6 +57,11 @@ HELPDESCRIPTION
 			this is a simple command, it can also be passed as such.
 			${fileMarker:+Inside CMD, $fileMarker is replaced with FILE (so that you do not
 			need to specify it twice).}
+    --exec CMD [...] ${MEMOIZEFILE_EXEC_END}	Execute CMD to update the FILE; all following arguments
+			are taken to be arguments to the CMD until an argument
+			consisting of '${MEMOIZEFILE_EXEC_END}' is encountered. ${fileMarker:+Inside CMD, $fileMarker is
+			replaced with FILE (so that you do not need to specify
+			it twice).}
 EXIT STATUS:
     0	FILE exists (and is recent enough), or had to be updated and that
 	succeeded.
@@ -102,6 +108,22 @@ do
 	--tee)		shift; isTee=t; teeContents() { cat -- "${1:?}" || exit 3; };;
 	--timestamp|-T)	shift; now="$1"; shift;;
 	--command|-c)	shift; commands+="${commands:+ $MEMOIZEFILE_COMMAND_JOINER }$1"; shift;;
+	--exec)		shift
+			cmd=
+			printf -v escapedFileMarker %q "$fileMarker"
+			while [ $# -gt 0 -a "$1" != "$MEMOIZEFILE_EXEC_END" ]
+			do
+			    printf -v quotedArg %q "$1"
+			    cmd+="${cmd:+ }${quotedArg//"$escapedFileMarker"/$fileMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${MEMOIZEFILE_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+="${commands:+ $MEMOIZEFILE_COMMAND_JOINER }${cmd}"
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
diff --git a/bin/memoizeLines b/bin/memoizeLines
--- a/bin/memoizeLines
+++ b/bin/memoizeLines
@@ -3,12 +3,13 @@ set -o pipefail
 shopt -qs extglob
 
 : ${MEMOIZELINES_COMMAND_JOINER=|}
+: ${MEMOIZELINES_EXEC_END=;}
 : ${MEMOIZELINES_ARG_MARKER='{}'}
 argMarker="$MEMOIZELINES_ARG_MARKER"; unset MEMOIZELINES_ARG_MARKER
 
 printShortUsage()
 {
-    printf 'Usage: cat SOURCE-FILE [...] | [MEMOIZELINES_FORCE_UPDATE=1|t|true|"LINE-GLOB"] %q %s\n' "$(basename "$1")" '[-v|--verbose [-v|--verbose]] [-s|--size N] [-t|--timeout|--for VALID-TIMESPAN[SUFFIX]] [-T|--timestamp EPOCH] [-w|--persist NAME [-i|--id ID]] [-d|--drop-on N] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    printf 'Usage: cat SOURCE-FILE [...] | [MEMOIZELINES_FORCE_UPDATE=1|t|true|"LINE-GLOB"] %q %s\n' "$(basename "$1")" "[-v|--verbose [-v|--verbose]] [-s|--size N] [-t|--timeout|--for VALID-TIMESPAN[SUFFIX]] [-T|--timestamp EPOCH] [-w|--persist NAME [-i|--id ID]] [-d|--drop-on N] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${MEMOIZELINES_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -60,6 +61,12 @@ HELPDESCRIPTION
 			line is read from standard output.
 			When this is a simple command, it can also be passed as
 			such.
+    --exec CMD [...] ${MEMOIZELINES_EXEC_END}	Execute CMD to transform a line; all following arguments
+			are taken to be arguments to the CMD until an argument
+			consisting of '${MEMOIZELINES_EXEC_END}' is encountered; ${argMarker:+inside CMD, $argMarker is
+			replaced with the line. Else,} the input is passed via
+			standard input. The transformed line is read from
+			standard output.
 EXIT STATUS:
     0	Lines either existed (and are recent enough), or had to be updated and
 	that succeeded.
@@ -105,6 +112,22 @@ do
 	--id|-i)	shift; id="$1"; shift;;
 	--drop-on|-d)	shift; dropOn="$1"; shift;;
 	--command|-c)	shift; commands+="${commands:+ $MEMOIZELINES_COMMAND_JOINER }$1"; shift;;
+	--exec)		shift
+			cmd=
+			printf -v escapedArgMarker %q "$argMarker"
+			while [ $# -gt 0 -a "$1" != "$MEMOIZELINES_EXEC_END" ]
+			do
+			    printf -v quotedArg %q "$1"
+			    cmd+="${cmd:+ }${quotedArg//"$escapedArgMarker"/$argMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${MEMOIZELINES_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+="${commands:+ $MEMOIZELINES_COMMAND_JOINER }${cmd}"
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
@@ -114,11 +137,11 @@ if [ $# -ne 0 ]; then
     # Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
     # undo the effects of eval.
     printf -v quotedSimpleCommand '%q ' "$@"
-    printf -v escapedFileMarker %q "$argMarker"
-    commands+="${commands:+ $MEMOIZELINES_COMMAND_JOINER }${quotedSimpleCommand//"$escapedFileMarker"/$argMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
+    printf -v escapedArgMarker %q "$argMarker"
+    commands+="${commands:+ $MEMOIZELINES_COMMAND_JOINER }${quotedSimpleCommand//"$escapedArgMarker"/$argMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
 fi
 if [ -z "$commands" ]; then
-    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo "ERROR: No COMMAND(s) specified; need to pass -c|--command \"COMMANDLINE\", or --exec SIMPLECOMMAND [...] $MEMOIZELINES_EXEC_END or SIMPLECOMMAND."
     echo
     printUsage "$0"
     exit 2
